### ISSUE TITLE
Daily TODO list 2017 Jan

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#10]
💭 
- [x] rewrite backend project transaction supplier track page
- [x] 已支付，才可以点击下一步
  - [x] http://localhost:8000/backend/project/29/transaction/order
- [ ] phpstorm high cpu

**Comment by itomg** [comment]
#### 2017-01-03 ☁️ 
- [ ] test myproject pages

**Comment by itomg** [comment]
#### 2017-01-04 ☀️ 
- [ ] igbug 143 148 151 157

**Comment by itomg** [comment]
#### 2017-01-05 ☀️ 
- [ ] igbug 161

**Comment by itomg** [comment]
#### 2017-01-06 ☁️ 
- [ ] igbug 162

**Comment by itomg** [comment]
#### 2017-01-06 ☁️ 
- [ ] igbug 162

**Comment by itomg** [comment]
#### 2017-01-09 ☀️ 
- [ ] igbug -166

**Comment by itomg** [comment]
#### 2017-01-10 ☀️ 
- [x] igbug 166

**Comment by itomg** [comment]
#### 2017-01-11 ☀️ 
- [ ] igbug 167

**Comment by itomg** [comment]
#### 2017-01-12 ☀️ 
- [ ] test project workflow online

**Comment by itomg** [comment]
#### 2017-01-13 ⛅️ 
- [ ] test online

**Comment by itomg** [comment]
#### 2017-01-16 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-01-17 ☀️ 
- [ ] region 三个的时候需要自动加载县区信息

**Comment by itomg** [comment]
#### 2017-01-18 ☁️ 
- [ ] upload files for project log
- [ ] project install check payment before next

**Comment by itomg** [comment]
#### 2017-01-19 ☁️ 
- [ ] igbug 170
- [ ] bugs from qq

**Comment by itomg** [comment]
#### 2017-01-20 ☁️ 
- [ ] symfony i18n

**Comment by itomg** [comment]
#### 2017-01-23 :sunny:
- [ ] symofny i18n

**Comment by itomg** [comment]
#### 2016-01-24 ☀️ 
- [ ] bug from qq msg 28

**Comment by itomg** [comment]
#### 2017-01-25 ☀️ 
- [ ] symfony i18n

**Comment by itomg** [comment]
#### 2017-01-26 ☁️ 
- [ ] tracking branch

**Comment by itomg** [comment]
#### 2017-01-27 - 2017-02-02 Happy New Year 😄
