### ISSUE TITLE
Daily TODO list 2017 Feb

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#11]
💭 
- [ ] phpstorm high cpu
- [x] send consult with queueable command

**Comment by itomg** [comment]
#### 2017-02-03 ☀️ 
- [ ] qq msg bug 32 34 35

**Comment by itomg** [comment]
#### 2017-02-04 ☀️ 
- [ ] symfony i18n

**Comment by itomg** [comment]
#### 2017-02-06 ☀️ 
- [ ] 过一下接下来的安排

**Comment by itomg** [comment]
#### 2017-02-07 ☀️ 
- [ ] delete solution category script

**Comment by itomg** [comment]
#### 2017-02-08 ⛅️ 
- [ ] show project_category_content_header & project_category_content
- [ ] equipment_brand & equipment tables
- [ ] backend project design device page select equipment
- [ ] solution case add more fields
- [ ] backend 2 levels menu

**Comment by itomg** [comment]
#### 2017-02-09 ☁️ 
- [ ] backend 2 levels menus

**Comment by itomg** [comment]
#### 2017-02-10 ☁️ 
- [ ] qq msg bugs 43 44 45 46 47
- [ ] learn symfony 的 moibleBundle

**Comment by itomg** [comment]
#### 2017-02-13 ☀️ 
- [ ] learn symfony mobileBundle

**Comment by itomg** [comment]
#### 2017-02-14 ☀️ 
- [ ] 方案与设计 显示 应用领域 暂时显示前6个项目分类
- [ ] 产品与报价 同上
- [ ] 方案与设计 显示 5个应用领域下的 做点击滚动效果 
- [ ] 应用领域显示图片
- [ ] 6.2 方案与设计 搜索结果 更新内容显示格式

**Comment by itomg** [comment]
#### 2017-02-15 ☁️ 
- [ ] https://dev.byechao.com/app_dev.php/solution/list/102
- [ ] remove 
- [ ] breadcrumb 修改
- [ ] 方案与设计=》应用领域（锚标记）=》方案
- [ ] page limit 4 -> 10
  - https://dev.canior.cn/ingreen/web/app_dev.php/product/list/13
    - [ ] 地区 去掉 省 市 自治区
  - https://dev.canior.cn/ingreen/web/app_dev.php/supplier/list/

**Comment by itomg** [comment]
#### 2017-02-16 ☀️
- [ ] staging error logs
  - [x] favicon.ico not found
  - [x] screen-lock.html not found
- [ ] tactician queueable command

**Comment by itomg** [comment]
#### 2017-02-17 ⛅️ 
- [ ] 短信接口 注册 忘记密码 免费咨询

**Comment by itomg** [comment]
#### 2017-02-20 ☀️ 
- [ ] ibugs

**Comment by itomg** [comment]
#### 2017-02-21 ☀️ 
- [ ] en consult
- [ ] wechat login api

**Comment by itomg** [comment]
#### 2017-02-22 ☁️ 
- [ ] wechat login

**Comment by itomg** [comment]
#### 2017-02-23 ☀️ 
- [x] igbug 183
- [ ] wechat login

**Comment by itomg** [comment]
#### 2017-02-23 ☀️ 
- [x] igbug 183
- [ ] wechat login

**Comment by itomg** [comment]
#### 2017-02-24 ☀️ 
- [ ] wechat login

**Comment by itomg** [comment]
#### 2017-02-27 ☀️ 
- [ ] igbug 186
- [ ] igbug 153
- [ ] wechat 客服消息？

**Comment by itomg** [comment]
#### 2017-02-28 ☁️ 
- [ ] igbug 153
- [ ] wechat 模板消息
