### ISSUE TITLE
Daily TODO list 2017 Mar

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#12]
💭 
- 海口
- 三亚
- 南宁
- 昆明
- 大理
- 丽江

- [ ] phpstorm high cpu
- [x] oauth user empty business

#### pull request link
- https://github.com/canior/ingreen/compare/sprint6...[branch]?expand=1

#### new open resource
- http://supervisord.org/ 开启多个 php 进程管理？

**Comment by itomg** [comment]
#### 2017-03-01 ☀️ 海口
- [ ] igbug 193
- [ ] wechat template message

**Comment by itomg** [comment]
#### 2017-03-02 ☀️ 
- [ ] wechat customer message

**Comment by itomg** [comment]
#### 2017-03-02 ☀️ 
- [ ] wechat customer message

**Comment by itomg** [comment]
#### 2017-03-03 :cloud:
- [ ] wechat open login

**Comment by itomg** [comment]
#### 2017-03-06 ☁️ 
- [ ] 230
- [ ] wechat open login

**Comment by itomg** [comment]
#### 2017-03-07 ⛅️ 
- [ ] igbug 203 205
  - https://modernizr.com/docs/#polyfills

**Comment by itomg** [comment]
#### 2017-03-08 ⛅️ 
- [ ] igbug 240
- [ ] igbug 203 205

**Comment by itomg** [comment]
#### 2017-03-09 ☀️ 
- [ ] wechat open login

**Comment by itomg** [comment]
#### 2017-03-10 ☀️
- [ ] wechat customer message

**Comment by itomg** [comment]
#### 2017-03-12 ☀️ 
- [x] fix email template bugs
  - [x] image absolute url
  - [x] change phone to name
  - [x] change subject to Chinese

**Comment by itomg** [comment]
#### 2017-03-13 ☀️ 
- [ ] 免费咨询发邮件给 sales

**Comment by itomg** [comment]
#### 2017-03-14 :sunny:
- [ ] 去掉产品列表的（）
- [ ] igbug 251
- [ ] igbug 252
- [ ] igbug 253

**Comment by itomg** [comment]
#### 2017-03-15 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-03-16 ⛅️ 
- [ ] wechat mp testing

**Comment by itomg** [comment]
#### 2017-03-17 ☁️ 
- [ ] change mp login workflow

**Comment by itomg** [comment]
#### 2017-03-19 :rain:
- [x] hide frontend solution case

**Comment by itomg** [comment]
#### 2017-03-20 ⛅️ 
- [ ] task design standard download

**Comment by itomg** [comment]
#### 2017-03-21 🌧 
- [ ] task?

**Comment by itomg** [comment]
#### 2017-03-22 ⛅️ 
- [ ] task refactor frontend solution case views

**Comment by itomg** [comment]
#### 2017-03-23 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-03-24 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-03-27 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-03-28 ☀️ 
- [ ] igbug 267

**Comment by itomg** [comment]
#### 2017-03-29 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-03-30 ☔️ 
- [ ] igbug 270

**Comment by itomg** [comment]
#### 2017-03-31 ☀️ 
- [ ] ?
