### ISSUE TITLE
Daily TODO list 2017 Apr

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#13]
💭 
- 丽江
- 上海

- [ ] phpstorm high cpu
- [ ] overwrite 404 500 page
- [ ] 后台用户管理
- [ ] 查询接口的数据库表设计
- [ ] 查询接口的页面设计
- [ ] 视频流对接方式搜索
- [ ] 脚本调用页面设计
- [ ] crane no list in config file

**Comment by itomg** [comment]
#### 2017-04-01 ?

**Comment by itomg** [comment]
#### 2017-04-05 ☁️ 
- [ ] igbug 274
- [ ] igbug 276
- [ ] igbug 277

**Comment by itomg** [comment]
#### 2017-04-06 ☀️ 
- [ ] symfony

**Comment by itomg** [comment]
#### 2017-04-07 ☀️ 
- [ ] symfony

**Comment by itomg** [comment]
#### 2017-09-10 ☔️ 
- [ ] wechat
- [ ] backend analytics

**Comment by itomg** [comment]
#### 2017-04-11 🌧 
- [x] tracking analysis user
- [ ] tracking analysis referer
- [ ] init WELL-E framework

**Comment by itomg** [comment]
#### 2017-04-12 ⛅️ 
- [ ] tracking analysis referer

**Comment by itomg** [comment]
#### 2017-04-13 ☀️ 
- [x] fix requestToken to userToken

**Comment by itomg** [comment]
#### 2017-04-14 ☀️ 
- [ ] 梳理新的流程设计

**Comment by itomg** [comment]
#### 2017-04-15 ☀️ 
- [ ] 解决几个问题
  - [ ] 引入模板
  - [ ] 配置多个数据库连接
  - [ ] 建立 issues

**Comment by itomg** [comment]
#### 2017-04-16 :sunny:
- [ ] import theme

**Comment by itomg** [comment]
#### 2017-04-17 🌧 
- [ ] 码头，西井用户部门/类型
- [ ] 用户权限

**Comment by itomg** [comment]
#### 2017-04-18 ☀️ 
- [x] task about product family selection

**Comment by itomg** [comment]
#### 2017-04-19 ☀️ 
- [ ] rail container search

**Comment by itomg** [comment]
#### 2017-04-20 ☀️ 
- [ ] rail container search
  - [ ] new table columns
  - [ ] download cvs
  - [ ] download img
  - [ ] trend chart

**Comment by itomg** [comment]
#### 2017-04-21 ☁️ 
- [ ] download pdf report

**Comment by itomg** [comment]
#### 2017-04-24 ☁️ 
- [ ] download img

**Comment by itomg** [comment]
#### 2017-04-25 ☁️ 
- [ ] jszip

**Comment by itomg** [comment]
#### 2017-04-26 ☔️ 
- [ ] bridge crane

**Comment by itomg** [comment]
#### 2017-04-27 ☁️ 
- [x] igbug 289
- [x] igbug 294

**Comment by itomg** [comment]
#### 2017-04-28 ☀️
- [ ] download image
