### ISSUE TITLE
Daily TODO list 2017 May

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#14]
💭 

- [x] 后台用户管理
- [ ] 视频流对接方式搜索
- [x] 脚本调用页面设计

**Comment by itomg** [comment]
#### 2017-05-01 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-05-02 ☔️ 
- [ ] rtsp page

**Comment by itomg** [comment]
#### 2017-05-03 ☁️ 
- [x] show rtsp on IE by VLC web plugin

**Comment by itomg** [comment]
#### 2017-05-04 ☔️ 
- [ ] search by CraneType
- [ ] search by IP

**Comment by itomg** [comment]
#### 2017-05-05 ☁️ 
- [x] igbug 299
- [x] show user email under project log user info
- [x] task disabled product categories not in the product family

**Comment by itomg** [comment]
#### 2017-05-06 ☀️ 
- [ ] login page
- [ ] logo

**Comment by itomg** [comment]
#### 2017-05-07 ☀️ 
- [ ] crane pages
  - green #48B87F
  - blue #009CE4
  - dark #222C38
  - gray #BFBFBF

**Comment by itomg** [comment]
#### 2017-05-08 ☔️ 
- [ ] task v1.5 01
- [ ] color

**Comment by itomg** [comment]
#### 2017-05-09 ⛅️ 
- [ ] task v1.5 02
- [ ] new style

**Comment by itomg** [comment]
#### 2017-05-10 ☀️ 
- [ ] task v1.5 02
  - [ ] “企业管理”下增加二级菜单“品牌管理”：内容包括品牌的增删改
  - [ ] 与厂商关联，其中选择厂商可采用弹出frame窗口

**Comment by itomg** [comment]
#### 2017-05-11 🌤 
- [ ] task v1.5 03
- [ ] page styles

**Comment by itomg** [comment]
#### 2017-05-12 ☔️ 
- [ ] remote operation platform
- [ ] task v1.5 04

**Comment by itomg** [comment]
#### 2017-05-13 ☀️ 
- [ ] task v1.5 04

**Comment by itomg** [comment]
#### 2017-05-14 ☀️ 
- [ ] task v1.5 04
  - [ ] images with priority

**Comment by itomg** [comment]
#### 2017-05-15 ⛅️ 
- [ ] task v1.5 04

**Comment by itomg** [comment]
####2017-05-16 ☀️ 
- [ ] issue 23
- [ ] issue 25

**Comment by itomg** [comment]
#### 2017-05-17 ☀️ 
- [ ] task v1.5 05
- [ ] issue 23

**Comment by itomg** [comment]
#### 2017-05-18 ☀️ 
- [ ] task v1.5 05
  - [ ] project category package
- [ ] user action log

**Comment by itomg** [comment]
#### 2017-05-19 ☁️ 
- [ ] task v1.5 06
- [ ] camera page style

**Comment by itomg** [comment]
#### 2017-05-20 ☀️ 
- [ ] task v1.5 06

**Comment by itomg** [comment]
#### 2017-05-21 ☀️ 
- [x] task v1.5 06
- [ ] issue 23?

**Comment by itomg** [comment]
#### 2017-05-22 ☀️ 
- [ ] issue 22
- [ ] task v1.5 07

**Comment by itomg** [comment]
#### 2017-05-23 ☔️ 
- [x] task v1.5 07
- [x] login page title
- [ ] config gate,bridge,rail
- [ ] token unique index

**Comment by itomg** [comment]
#### 2017-05-24 🌂 
- [ ] configable gate,bridge,rail
- [ ] token unique index

**Comment by itomg** [comment]
#### 2017-05-25 ☀️ 
- [ ] issue 27
- [ ] v1.5 template

**Comment by itomg** [comment]
#### 2017-05-26 :sunny:
- [ ] task v1.5 home page

**Comment by itomg** [comment]
#### 2017-05-27 ☀️ 
- [ ] task v1.5 home page ip and menus
- [ ] user add

**Comment by itomg** [comment]
#### 2017-05-28 ☀️ 
- [x] user CRUD

**Comment by itomg** [comment]
#### 2017-05-29 ☀️ 
- [ ] user pagination

**Comment by itomg** [comment]
#### 2017-05-31 ☀️ 
- [x] load json file run script
- [ ] task v1.5 find product
