### ISSUE TITLE
Daily TODO list 2017 June

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#15]
💭 

- [ ] 视频流对接方式搜索
- [ ] frontend v1.5 page titles

**Comment by itomg** [comment]
#### 2017-06-01 ☔️ 
- [ ] task v1.5 find product detail

**Comment by itomg** [comment]
#### 2017-06-02 ☁️ 
- [ ] task v1.5 find product detail list
- [ ] task v1.5 find product detail list item

**Comment by itomg** [comment]
#### 2017-06-04 ☀️ 
- [ ] task v1.5 find product detail list item

**Comment by itomg** [comment]
#### 2017-06-05 🌂 
- [ ] design error log table
- [ ] task v1.5 find product detail list item

**Comment by itomg** [comment]
#### 2017-06-06 ☁️ 
- [ ] error log table

**Comment by itomg** [comment]
#### 2017-06-07 ☁️ 
- [ ] rtsp to rtmp?

**Comment by itomg** [comment]
#### 2017-06-08 ☁️ 
- [ ] find plan
  - 选购指南banner=>分类组子页面
  - 热门咨询banner=>对应的应用领域的子页面

**Comment by itomg** [comment]
#### 2017-06-09 ☁️ 
- [x] fix a bug projectCategoryPackageProduct.product.defaultImageFile
- [ ] find plan main page
- [ ] test nginx-rtmp-module

**Comment by itomg** [comment]
#### 2017-06-10 ☔️ 
- [ ] V1.5－找方案－主页面
- [ ] V1.5－找方案－子页面（指定参数application_area_id）

**Comment by itomg** [comment]
#### 2017-06-11 ☀️ 
- [ ] V1.5－找方案－主页面

**Comment by itomg** [comment]
#### 2017-06-12 ☔️ 
- [ ] V1.5－找方案－子页面（指定参数application_area_id）
- [ ] V1.5－找方案－场景主页面、场景详情页（指定参数application_scene_id）

**Comment by itomg** [comment]
#### 2017-06-13 ☁️ 
- [ ] V1.5－找产品－品牌推荐、产品保障
- [ ] V1.5－找方案－资讯主页面、列表页、详情页
- [ ] V1.5－找方案－看案例、案例详情（solution_case_id）
- [ ] V1.5－找方案－厂商推荐、厂商详情页、服务保障

**Comment by itomg** [comment]
#### 2017-06-14 ☁️ 
- [x] V1.5－找方案－看案例、案例详情（solution_case_id）
- [x] V1.5－找方案－厂商推荐、厂商详情页、服务保障

**Comment by itomg** [comment]
#### 2017-06-15 ☀️ 
- [ ] search pages
- [ ] rtsp to hls

**Comment by itomg** [comment]
#### 2017-06-16 ☁️ 
- [x] search product
- [x] search plan

**Comment by itomg** [comment]
#### 2017-06-18 ☁️ 
- [ ] rtsp 2 rtmp
- [ ] user and record new field 港口
- [ ] select ip

**Comment by itomg** [comment]
#### 2017-06-18 ☁️ 
- [ ] rtsp 2 rtmp
- [ ] user and record new field 港口
- [ ] select ip

**Comment by itomg** [comment]
#### 2016-06-19 ☔️ 
- [ ] convert region name 汉字 to pinyin
- [ ] add a new field for harbor raw table?
- [ ] list all harbor values for admin to select for user?
- [ ] load raw records by user harbors

**Comment by itomg** [comment]
#### 2017-06-20 🌧 
- [ ] issue 43

**Comment by itomg** [comment]
#### 2017-06-21 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-06-22 ⛅️ 
-  [x] igbug 340 342 343 345 
- [ ] 347

**Comment by itomg** [comment]
#### 2017-06-23 ☀️ 
- [ ] cookie
- [ ] ftp server

**Comment by itomg** [comment]
#### 2017-06-25 ☀️ 
- [ ]

**Comment by itomg** [comment]
#### 2017-06-26 ☀️ 
- [ ] issue 37

**Comment by itomg** [comment]
#### 2017-06-27 ⛅️ 
- [ ] igbug 356

**Comment by itomg** [comment]
#### 2017-06-28 ☁️ 
- [ ] .73 staging branch clean useless bundles
