### ISSUE TITLE
Daily TODO list 2017 July

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#16]
💭 

- [x] gulp md5 css js min file

**Comment by itomg** [comment]
#### 2017-07-01 ☀️ 
- [ ] issue 47

**Comment by itomg** [comment]
#### 2017-07-02 ☀️ 
-  [ ] igbugs

**Comment by itomg** [comment]
#### 2017-07-03 ☁️ 
- [ ] igbugs

**Comment by itomg** [comment]
#### 2017-07-04 ☀️ 
- [x] issue 48
- [ ] css/js version
- [ ] camera hls branch

**Comment by itomg** [comment]
#### 2017-07-05 ☀️ 
- [ ] css/js version

**Comment by itomg** [comment]
#### 2017-07-06 ☀️ 
- [ ] igbugs 385 401 402 403

**Comment by itomg** [comment]
#### 2017-07-07 :sunny:
- [x] leeke's question https://jsfiddle.net/itomg/4jc6u6qk/

**Comment by itomg** [comment]
#### 2017-07-07 :sunny:
- [x] leeke's question
  - https://www.oschina.net/question/660023_2247162#form_answer
  - https://jsfiddle.net/itomg/4jc6u6qk/

**Comment by itomg** [comment]
#### 2017-07-08 ☁️ 
- [ ] css js

**Comment by itomg** [comment]
#### 2017-07-09 ☀️ 
- [ ] info collect
  - http://www.zhongkerd.com/news/content-729.html
  - https://segmentfault.com/a/1190000004963423

**Comment by itomg** [comment]
#### 2017-07-10 ☁️ 
- [x] new project offer
- [ ] tech collect

**Comment by itomg** [comment]
#### 2017-07-11 ☀️ 
- [ ] igbugs

**Comment by itomg** [comment]
#### 2017-07-12 ☔️ 
- [ ] mobile pages
  - [ ] home page
    - [ ] switch city
    - [ ] search form
  - [ ]

**Comment by itomg** [comment]
#### 2017-07-13 ☀️ 
- [ ] mobile v1.5 pages

**Comment by itomg** [comment]
#### 2017-07-14 ☁️ 
- [ ]  mobile v1.5 pages
  - [ ] find plan main
  - [ ] find plan
  - [ ] find plan
  - [ ] find plan
  - [ ] find plan
  - [ ] find plan
  - [ ] find plan
  - [ ] find plan
  - [ ] find plan
  - [ ] find plan

**Comment by itomg** [comment]
#### 2017-07-15 ☀️ 
- [ ]  mobile v1.5 pages
  - [ ] find plan hot ➡️  find-plan-mes
  - [ ] find plan mes ➡️  find-plan-mes-list-item?

**Comment by itomg** [comment]
#### 2017-07-16 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-07-17 ☁️ 
- [ ] mobile v1.5 pages

**Comment by itomg** [comment]
#### 2017-07-18 ☁️ 
- [ ] ???

**Comment by itomg** [comment]
#### 2017-07-19 🌂 
- [ ] mobile v1.5 pages
  - [ ] login
  - [ ] register

**Comment by itomg** [comment]
#### 2017-07-20 ☁️ 
- [x] igbug 431

**Comment by itomg** [comment]
#### 2017-07-21 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-07-22 ☀️ 
- [ ] igbug 432

**Comment by itomg** [comment]
#### 2017-07-23 ☀️ 
- [ ] igbug 432

**Comment by itomg** [comment]
#### 2017-07-24 ⛅️ 
- [ ] igbug 432

**Comment by itomg** [comment]
#### 2017-07-25 ☀️ 
- [ ] igbug 433
- [ ] igbug 434

**Comment by itomg** [comment]
#### 2017-07-26 ☀️ 
- [ ] oobe

**Comment by itomg** [comment]
#### 2017-07-27 ⛅️ 
- [ ] oobe

**Comment by itomg** [comment]
#### 2017-07-28 🌂 
- [ ] wifi auto connect

**Comment by itomg** [comment]
#### 2017-07-29 ☀️ 
- [ ] OOBE
  - [ ] yaml persistent
  - [ ] DataAccess

**Comment by itomg** [comment]
#### 2017-07-30 ☀️ 
- [ ] gulpfile
- [ ] bower
- [ ] bootstrap
- [ ] jquery

**Comment by itomg** [comment]
#### 2017-07-31 ☀️ 
- [ ] init timezone page
