### ISSUE TITLE
Daily TODO list 2017 Aug

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#17]
💭 
- [x] 更新 ini 文件
- [x] rtsp to hls
- [ ] select image area to get position  coordinate
- [ ] shutdown
- [ ] reboot
- [ ] set cameras ip

**Comment by itomg** [comment]
#### 2017-08-01 ☁️ 
- [ ] symfony timezone

**Comment by itomg** [comment]
#### 2017-08-02 ☔️ 
- [x] init ip preview
- [ ] user login

**Comment by itomg** [comment]
#### 2017-08-03 🌂 
- [x] igbug 439
- [x] igbug 441
- [ ] igbug ?

**Comment by itomg** [comment]
#### 2017-08-04 :cloud:
- [ ] fix pr 740

**Comment by itomg** [comment]
#### 2017-08-05 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-08-06 ☁️ 
- [ ] user provider

**Comment by itomg** [comment]
#### 2017-08-07 ☁️ 
- [ ] igbugs
- [ ] issue 3/4

**Comment by itomg** [comment]
#### 2017-08-08 :cloud:
- [x] igbugs 478 477 475 456 448
- [ ] issue 3/4
- [ ] discuss with ED about post data to his interface

**Comment by itomg** [comment]
#### 2017-08-09 ☁️ 
- [ ] finish all pages
- [ ] area to region
- [ ] ini

**Comment by itomg** [comment]
#### 2017-08-10 ☁️ 
- [ ] find product brand
- [ ] ini save
- [ ] step save and update ini
- [ ] region plugin

**Comment by itomg** [comment]
#### 2017-08-11 ☁️ 
- [ ] mktv
- [ ] region

**Comment by itomg** [comment]
#### 2017-08-12 ☁️ 
- [ ] remove doctrine ORM
- [ ] run rtmp to hls process
- [ ] logout modal
- [ ] user login page
- [ ] region plugin
- [ ] post to wellpetrol

**Comment by itomg** [comment]
#### 2017-08-13 ☀️ 
- [ ] logout reset modal
- [ ]  user login page
- [ ] region selection

**Comment by itomg** [comment]
#### 2017-08-14 🌫 
- [ ] 大华，其它

**Comment by itomg** [comment]
#### 2017-08-15 🌫 
- [ ] reboot shutdown
- [ ] style

**Comment by itomg** [comment]
#### 2017-08-17 ☀️ 
- [ ] test and fix bug

**Comment by itomg** [comment]
#### 2017-08-18 ☁️ 
- [ ] custom 404 500 pages
- [ ] test config ip and other scripts

**Comment by itomg** [comment]
#### 2017-08-21 ☀️ 
- [x] igbugs
- [ ] old version changes

**Comment by itomg** [comment]
#### 2017-08-22 ☁️ 
- [ ] igbug 509

**Comment by itomg** [comment]
#### 2017-08-23 ☁️ 
- [x] igbug 531
- [ ] Easy_Script

**Comment by itomg** [comment]
#### 2017-08-24 ☁️ 
- [x] fix pr 818 819

**Comment by itomg** [comment]
#### 2017-08-28 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-08-31 ☀️ 
- [x] PR 831

**Comment by itomg** [comment]
#### 2017-08-31 ☀️ 
- [ ] vue?
