### ISSUE TITLE
Daily TODO list 2017 Sep

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#18]
💭 
- [ ] welle
- [ ] mktv

**Comment by itomg** [comment]
#### 2017-09-01 ☀️ 
- [ ] mktv task 1
- [ ] mktv task 2

**Comment by itomg** [comment]
#### 2017-09-02 🌧 
- [ ] {# TODO: config.filebrowserImageUploadUrl = '{{ path('imageUpload') }}'; #}
- [ ]

**Comment by itomg** [comment]
#### 2017-09-03 ☀️
- [ ] Device pages 
- [ ] RoomDeviceLog

**Comment by itomg** [comment]
#### 2017-09-04 ☀️ 
- [ ] market pages?

**Comment by itomg** [comment]
#### 2017-09-05 ⛅️ 
- [ ] tag pages
- [ ] market pages

**Comment by itomg** [comment]
#### 2017-09-06 ☀️ 
- [ ] market
  - [ ] contracts
  - [ ] floors

**Comment by itomg** [comment]
#### 2017-09-07 ☀️ 
- [ ] welle
- [ ] many to many tags
- [ ] market images

**Comment by itomg** [comment]
- [ ] welle interval reload
- [ ] 运营维护->房间状态

**Comment by itomg** [comment]
#### 2017-09-09 ☀️ 
- [ ] market sub tags

**Comment by itomg** [comment]
#### 2017-09-10 ☁️ 
- [ ] welle vue
  - https://www.cloudways.com/blog/rest-api-in-symfony-3-1/

**Comment by itomg** [comment]
#### 2017-09-11 ☀️ 
- [ ] common circle component
- [ ] split cam latency
- [ ] accuracy rate

**Comment by itomg** [comment]
#### 2017-09-12 ☀️ 
- [ ] mktv
  - [ ] backend user pages

**Comment by itomg** [comment]
#### 2017-09-13 ☀️ 
- [ ] welle
  - [ ]  screen 4
- [ ] doctrine transaction
- [ ] symfony entity register post load methods

**Comment by itomg** [comment]
#### 2017-09-14 ☀️ 
- [ ] sysinfo postload

**Comment by itomg** [comment]
#### 2017-09-15 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-09-16 ☁️ 
- [ ] api todo
  - https://tech.meituan.com/lucene-distance.html
  - https://fukun.org/archives/06152067.html
  - https://tiicle.com/items/217/php-according-to-latitude-and-longitude-to-find-people-nearby

**Comment by itomg** [comment]
#### 2017-09-18 🌦 
- [ ] welle 2 places changed
- [ ] mktv

**Comment by itomg** [comment]
#### 2017-09-19 ☀️ 
- [ ] mktv changes

**Comment by itomg** [comment]
#### 2017-09-20 ☀️ 
- [ ] igbug
- [ ] mktv qrcode

**Comment by itomg** [comment]
#### 2017-09-21 ☀️ 
- [ ] C0-9
- [ ] C0-12
- [ ] C0-11

**Comment by itomg** [comment]
#### 2017-09-22 ☁️ 
- [x] down QRCode bundle version
- [x] mktv support

**Comment by itomg** [comment]
#### 2017-09-23 ☀️ 
- [ ] send red command

**Comment by itomg** [comment]
#### 2017-09-25 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-09-28 ☀️ 
- [ ] command message

**Comment by itomg** [comment]
#### 2017-09-29 ☁️ 
- [ ] 计划任务开锁 （调用所有未完成，未支付，同时智能锁的状态是关的订单，打开锁） 不让客户在玩儿的过程中关门
