### ISSUE TITLE
Daily TODO list 2017 Oct

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#19]
💭 
- [ ] EDI

**Comment by itomg** [comment]
#### 2017-10-09 ☔️ 
- [ ] EDI init

**Comment by itomg** [comment]
#### 2017-10-10 ☀️ 
- http://open.iqiyi.com/lib/play.html

**Comment by itomg** [comment]
#### 2017-10-11 ☁️ 
- [ ] EDI

**Comment by itomg** [comment]
#### 2017-10-12 ☀️ 
- [ ] EDI

**Comment by itomg** [comment]
#### 2017-10-13 ☁️ 
- [x] mktv backend changes
- [ ] EDI workflow

**Comment by itomg** [comment]
#### 2017-10-14 ⛅️ 
- [ ] 服务器端更改金额

**Comment by itomg** [comment]
#### 2017-10-16 ☀️ 
- [ ] EDI 完成第一页，第二页
- [ ] mktv bugs

**Comment by itomg** [comment]
#### 2017-10-17 ☀️ 
- [ ] https://pkg.phpcomposer.com/

**Comment by itomg** [comment]
#### 2017-10-18 ☀️ 
- [ ] EDI
- [ ] MKTV plan

**Comment by itomg** [comment]
#### 2017-10-19 ☁️ 
- [ ] EDI screen 3

**Comment by itomg** [comment]
#### 2017-10-20 ☀️ 
- [ ] EDI
  - [ ] get docResult after ocrDone or every time?
  - [ ] style to display docResult
  - [ ] download what?
- [ ] mktv
  - backend lock list
  - wechat open user register

**Comment by itomg** [comment]
#### 2017-10-21 ☀️ 
- [ ] EDI screen 3 docResult

**Comment by itomg** [comment]
#### 2017-10-23 ☀️ 
- [ ] mktv backend prices
- [ ] Well-e 闸口

**Comment by itomg** [comment]
#### 2017-10-24 ☀️ 
- [ ] Well-e gate

**Comment by itomg** [comment]
#### 2017-10-25 ☁️ 
- [ ] well-e

**Comment by itomg** [comment]
#### 2017-10-26 ☁️ 
- [ ] mktv backend user price add mark

**Comment by itomg** [comment]
#### 2017-10-30 ☀️ 
- [ ] Edi well-e

**Comment by itomg** [comment]
#### 2017-10-31 ☀️ 
- [ ] well-e
- [ ] mktv bugs
