### ISSUE TITLE
Daily TODO list 2017 Nov

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#20]
💭

**Comment by itomg** [comment]
#### 2017-11-01 ☁️ 
- [ ] WellVision

**Comment by itomg** [comment]
#### 2017-11-02 ☁️ 
- [ ] WellVision
  - [ ] 技术框架选择
- [ ] well-e edi docs
- [ ] mktv
  - [ ] clear branches
  - [ ] bug C0-18

**Comment by itomg** [comment]
#### 2017-11-03 ☁️ 
- [ ] mktv bugs

**Comment by itomg** [comment]
#### 2017-11-06 ☀️
- [ ] well vision

**Comment by itomg** [comment]
#### 2017-11-07 ☁️ 
- https://github.com/vuejs/awesome-vue

**Comment by itomg** [comment]
#### 2017-11-08 ☔️ 
- [ ] WellVision
  - [ ] fosuserbundle
  - [ ] login

**Comment by itomg** [comment]
#### 2017-11-09 ☀️ 
- [ ] WellVision
  - [ ] login
  - [ ] home

**Comment by itomg** [comment]
#### 2017-11-10 ❄️ 
- [ ] WellVision
  - [ ] login

**Comment by itomg** [comment]
#### 2017-11-12 ☀️ 
- [ ] WV

**Comment by itomg** [comment]
#### 2017-11-13 ☁️ 
- [x] EDI download csv
  - https://symfony.com/blog/new-in-symfony-3-2-csv-and-yaml-encoders-for-serializer
- [ ] WV lane page

**Comment by itomg** [comment]
#### 2017-11-14 ☀️ 
- [ ] WV lane
- [ ] mktv bugs

**Comment by itomg** [comment]
#### 2017-11-15 ☀️ 
- [ ] WV lane
- [ ] mktv bugs

**Comment by itomg** [comment]
#### 2017-11-16 ☀️ 
- [ ] mktv C0-38
  - [x] 1.3 时段分析
    - https://github.com/flot/flot/blob/master/API.md

**Comment by itomg** [comment]
#### 2017-11-17 ☁️ 
- [ ] mktv C0-38
  - [x] 2.2 充值报告
  - [ ] 2.3 收入报告

**Comment by itomg** [comment]
#### 2017-11-19 ☀️ 
- [ ] WV 2.5

**Comment by itomg** [comment]
#### 2017-11-20 ☀️ 
- [ ] WV 2.5
- [ ] mktv bug

**Comment by itomg** [comment]
#### 2017-11-21 ☀️ 
- [ ] EDI 3 preview edit
- [ ] WV 2.5
- [ ] mktv bug

**Comment by itomg** [comment]
#### 2017-11-22 ☀️ 
- [ ] WV 2.5
- [ ] mktv bug 46

**Comment by itomg** [comment]
#### 2017-11-23 ☀️ 
- [ ] WV 3

**Comment by itomg** [comment]
#### 2017-11-24 ☀️ 
- [ ] WV 3 4 5

**Comment by itomg** [comment]
#### 2017-11-27 ☀️ 
- [ ] mktv C0-48

**Comment by itomg** [comment]
#### 2017-11-28 ☁️ 
- [ ] mktv C0-49

**Comment by itomg** [comment]
#### 2017-11-29 ☀️ 
- [ ] wxgz location

**Comment by itomg** [comment]
#### 2017-11-30 ☀️ 
- [ ] mktv C0-51/52/53

**Comment by itomg** [comment]
#### 2017-12-01 ☀️ 
- [ ] mktv 51 3 4
