### ISSUE TITLE
Daily TODO list 2017 Dec

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#21]
💭

**Comment by itomg** [comment]
#### 2017-12-01 ☀️ 
- [x] mktv 51 3
- https://www.zhihu.com/question/22525413

**Comment by itomg** [comment]
#### 2017-12-02 ☁️ 
- [ ] mktv 51 4

**Comment by itomg** [comment]
#### 2017-12-04 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-12-05 ☁️ 
- [ ] mktv C0-56

**Comment by itomg** [comment]
#### 2017-12-06 ☀️ 
💭

**Comment by itomg** [comment]
#### 2017-12-07 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2017-12-11 ⛅️ 
- [ ] WV user

**Comment by itomg** [comment]
#### 2017-12-12 ❄️ 
- [ ] mktv C0-59
- [ ] WV

**Comment by itomg** [comment]
#### 2017-12-13 ⛅️ 
- [ ] WV

**Comment by itomg** [comment]
#### 2017-12-14 ☀️ 
- [ ] WV admin users
  - https://github.com/thephpleague/omnipay
- [ ] chengxin

**Comment by itomg** [comment]
#### 2017-12-15 🌨 
- [ ] chengxin gmail
- [ ] WV letter avatar

**Comment by itomg** [comment]
#### 2017-12-18 ☁️ 
- [ ] WV
  - [ ] icons
  - [ ] letter avatar
- [ ] chengxin gmail

**Comment by itomg** [comment]
#### 2017-12-19 ☀️ 
- [ ] chengxin form to pdf

**Comment by itomg** [comment]
#### 2017-12-20 ☀️ 
- [ ] chengxin 1110

**Comment by itomg** [comment]
#### 2017-12-21 ☀️ 
- [ ] chengxin 1110 log
- [ ] mktv C0 60

**Comment by itomg** [comment]
#### 2017-12-22 ☀️ 
- [ ] welle 54 57 58
- [ ] mktv C0 60

**Comment by itomg** [comment]
#### 2017-12-23 ☀️ 
- [ ] chengxin 1055

**Comment by itomg** [comment]
#### 2017-12-25 ☀️ 
- [ ] chengxin 1055

**Comment by itomg** [comment]
#### 2017-12-26 ☀️ 
- [ ] chengxin 1055

**Comment by itomg** [comment]
#### 2017-12-27 ☀️ 
- [ ] chengxin gmail 发送模板中变量不替换
- [ ] alipay api

**Comment by itomg** [comment]
#### 2017-12-28 ☀️ 
- [ ] we wv log? user_id?

**Comment by itomg** [comment]
#### 2017-12-31 🌨 
- [ ] chengxin 2149
