### ISSUE TITLE
Daily TODO list 2018 Jan

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#22]
💭 
- [ ] vuejs + [koajs](http://koajs.com/) TODO

**Comment by itomg** [comment]
#### 2018-01-02 ☁️ 
- [ ] chengxin 1106

**Comment by itomg** [comment]
#### 2018-01-03 ☀️ 
- [x] WE 54
- [x] WV 3
- [ ] chengxin 1106

**Comment by itomg** [comment]
#### 2018-01-04 ☀️ 
- [x] mktv report order
- [ ] chengxin pdf

**Comment by itomg** [comment]
#### 2018-01-08 🌨 
- [ ] chengxin bugs

**Comment by itomg** [comment]
#### 2018-01-09 ☁️ 
- [ ] chengxin bugs

**Comment by itomg** [comment]
#### 2018-01-10 ☀️ 
- [ ] chengxin bugs

**Comment by itomg** [comment]
#### 2018-01-11 ☁️ 
- [ ] chengxin bugs

**Comment by itomg** [comment]
#### 2018-01-12 ☁️ 
- [ ] chengxin task 1106

**Comment by itomg** [comment]
#### 2018-01-15 ☀️ 
- [ ] chengxin bug

**Comment by itomg** [comment]
#### 2018-01-16 ☁️ 
- [ ] mktv return pay

**Comment by itomg** [comment]
#### 2018-01-17 ☁️ 
- [ ] PHPWord

**Comment by itomg** [comment]
#### 2018-01-18 ☀️ 
- [ ] PHPWord pdf writer
- [ ] mktv bug

**Comment by itomg** [comment]
#### 2018-01-19 ☀️ 
- [ ] chengxin bug D8-290 add log

**Comment by itomg** [comment]
#### 2018-01-22 :sunny:
- [ ] chengxin bug

**Comment by itomg** [comment]
#### 2018-01-23 ☀️ 
- [ ] mktv bug C0-72
- [ ] chengxin bug D8-293

**Comment by itomg** [comment]
#### 2018-01-24 ☀️ 
- [ ] chengxin bug D8-293

**Comment by itomg** [comment]
#### 2018-01-25 ☀️ 
- [ ] chengxin task 2251

**Comment by itomg** [comment]
#### 2018-01-29 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2018-01-30 ☀️ 
- [ ] chengxin 2332

**Comment by itomg** [comment]
#### 2018-01-31 ☀️ 
- [ ] mktv room statistics
