### ISSUE TITLE
Daily TODO list 2016 Jun

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#3]
💭 
#### 2016-06-13 ⭐
- [ ] canior tasks
- [ ] symfony 3
- [ ] doctrine 2
- [ ] tactition command bus
  - [ ] command bus
  - [ ] command
  - [ ] command handler
  - [ ] command bus middleware
- [ ] Q
  - [ ]  commandBus handle async to sync
- docs
  - https://symfony.com/doc/master/bundles/FOSUserBundle/command_line_tools.html
  - http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/query-builder.html
  - http://symfony.com/doc/current/cookbook/form/form_collections.html#template-modifications
  - http://symfony.com/doc/current/cookbook/serializer.html
  - http://twig.sensiolabs.org/documentation
  - http://www.dropzonejs.com/
  - https://api.jqueryui.com/spinner/
- tutorial online
  - http://knpuniversity.com/screencast/doctrine-queries/joins-reduce-queries#play

**Comment by itomg** [comment]
#### 2016-06-15 ☀️ 
- [ ] 1-4
- [ ] 1-7

**Comment by itomg** [comment]
#### 2016-06-16 ☁️ 
- [ ] 1-7
  - [ ] 试试dataAccess的读取和存储
  - [ ] 在ExampleController建一个你自己的testAction测试
  - [ ] create commands & command handlers

**Comment by itomg** [comment]
#### 2016-06-17 🌞 
- [ ] 1-7
  - [ ] refactor commands

**Comment by itomg** [comment]
2016-06-18 ☁️ 
- [ ] doc more phpstorm shortcuts
- [ ] 🏊 
- [ ] go tour

**Comment by itomg** [comment]
#### 2016-06-19
- [x] install arch linux
  - [x] i3 window manager
  - [ ] chrome

**Comment by itomg** [comment]
#### 2016-06-20 🌂 
- [ ] refactor region.sql
- [ ] 1-7?

**Comment by itomg** [comment]
#### 2016-06-21 ☁️ 
- [ ] 2-?
  - [ ] create test controller to test command
    - [ ] business
    - [ ] product
    - [ ] ...

**Comment by itomg** [comment]
#### 2016-06-22 ☔ 
- [ ] how to create a fos user
- [ ] CreateOrUpdateProductCategoryAttributeCommand and handler
- [ ] DeleteProductCategoryAttributeCommand and handler

**Comment by itomg** [comment]
#### 2016-06-23 ☀️ 
- [ ] learn

**Comment by itomg** [comment]
#### 2016-06-24 🌞 
- [ ] fix comments under PR
- [ ] refactor 3 tables to add field status
  - product_attribute
  - product_doc
  - product_specification
- [ ] 2-11

**Comment by itomg** [comment]
#### 2016-06-27 ☁️ 
- [ ] 产品管理增删改

**Comment by itomg** [comment]
#### 2016-06-28 ☔ 
- [ ] 2-12 
  - [ ] backend edit product
  - [ ] backend delete product

**Comment by itomg** [comment]
#### 2016-06-29 ☔ 
- [ ] 2-12 fix comments
  - [ ] backend product list

**Comment by itomg** [comment]
#### 2016-06-30 ☀️ 
- [ ] 互相测试，学习
