### ISSUE TITLE
Daily TODO list 2016 Jul

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#4]
💭 
#### frontend template

> http://remtsoy.com/tf_templates/the_box/demo_v1_6/index-layout-3.html#
#### local docs

> file:///Users/jimmyzhao/www/canior/docs/upload_v1_6/documentation/documentation/index.html#!/css_files

**Comment by itomg** [comment]
#### 2016-07-01 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-07-04
- [ ] 页面改成跟 business 一致，下拉菜单，input等，对照源代码，现在太乱
- [ ] 产品列表页面的属性赶快弄完
- [ ] 产品分类页面的属性值类型应该是个下拉菜单，不能让手写
- [ ] 添加编辑产品时，分类只能选择一个，只能是最底层分类，如果不是最底层应该显示错误信息

**Comment by itomg** [comment]
#### 2016-07-05 ☀️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-07-06 ☀️ 
- [ ]

**Comment by itomg** [comment]
#### 2016-07-07 ☁️ 
- [ ] 准备好所有需要重写的页面
- [ ] 修复并重写注册页面
- [ ] 引入前台页面
- [ ] 弄懂 user management

**Comment by itomg** [comment]
#### 2016-07-08 ⛅ 
- [ ] keep learning FosUserBundle

**Comment by itomg** [comment]
#### 2016-07-09 🌂 
- [ ] keep learning FosUserBundle

**Comment by itomg** [comment]
#### 216-07-10 ☀️ 
- [ ] 前台的方案详情的页面
  - frontend/SolutionController

**Comment by itomg** [comment]
#### 2016-07-11 ☀️ 
- [ ]

**Comment by itomg** [comment]
#### 2016-07-12 ☀️ 
- [ ] keep learning symfony fosUserBundle

**Comment by itomg** [comment]
#### 2016-07-13 ☔ 
- [ ] igbugs

**Comment by itomg** [comment]
#### 2016-07-14 ⛅ 
- [ ] bugs

**Comment by itomg** [comment]
#### 2016-07-15 ☁️ 
- [ ] keep learning symfony

**Comment by itomg** [comment]
#### 2016-07-18 ☀️ 
- [ ] keep learning symfony

**Comment by itomg** [comment]
#### 2016-07-19 ☀️ 
- [ ] keep learning symfony

**Comment by itomg** [comment]
#### 2016-07-20 ☀️ 
- [ ] keep learning symfony

**Comment by itomg** [comment]
#### 2016-07-21 ☀️ 
- [ ] keep learning symfony

**Comment by itomg** [comment]
#### 2016-07-22 ☁️ 
- [ ] keep learning symfony

**Comment by itomg** [comment]
#### 2016-07-25 ⛅ 
- [ ] keep learning symfony

**Comment by itomg** [comment]
#### 2016-07-26 ☔ 
- [x] upgrade phpstorm
- [ ] doctrine migration script
- [ ] entities and resources config
- [ ] createOrUpdate and delete commands
- [ ] backend pages

**Comment by itomg** [comment]
#### 2016-07-27 ☁️ 
- [ ] entities & config

**Comment by itomg** [comment]
#### 2016-07-28 ☀️ 
- [ ] createOrUpdate & delete commands

**Comment by itomg** [comment]
#### 2016-07-29 ☔ 
- [ ] createOrUpdate & delete commands
  - [ ] projectStatusLog
  - [ ] quotation
  - [ ] quotationComponent
  - [ ] quotationCost
  - [ ] supplierQuotation
  - [ ] supplierQuotationComponent
  - [ ] supplierQuotationCost
  - [ ] installQuotation
  - [ ] installQuotationComponent
  - [ ] installQuotationCost
  - [ ] installQuotationDoc
  - [ ] installerQuotation
  - [ ] installerQuotationCost
  - [ ] installerQuotationDoc
