### ISSUE TITLE
Daily TODO list 2016 Aug

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#5]
💭

**Comment by itomg** [comment]
#### 2016-08-01
- [ ] custom validators

**Comment by itomg** [comment]
#### 2016-08-02
- [ ] learnig

**Comment by itomg** [comment]
#### 2016-08-03
- [  ] backend project edit page

**Comment by itomg** [comment]
#### 2016-08-04 ☀️ 
- [ ] backend project design flow pages

**Comment by itomg** [comment]
#### 2016-08-05 ☁️ 
- [ ] backend project design flow pages

**Comment by itomg** [comment]
#### 2016-08-08 ☀️ ?
- [ ] backend project solution page

**Comment by itomg** [comment]
#### 2016-08-09 ☀️ 
- [ ] backend project solution cost page
- [ ] backend project solution doc page

**Comment by itomg** [comment]
#### 2016-08-10 ☁️ 
- [ ] backend project install flow pages

**Comment by itomg** [comment]
#### 2016-08-11 ☁️ 
- [ ] backend project install component page

**Comment by itomg** [comment]
#### 2016-08-12 ☀️ 
- [ ] backend project install quotation doc page

**Comment by itomg** [comment]
#### 2016-08-15 ☀️ 
- [ ] backend project installer quotation list page
- [ ] backend project installer quotation delete page

**Comment by itomg** [comment]
#### 2016-08-16 ☁️ 
- [ ] backend project installer track page

**Comment by itomg** [comment]
#### 2016-08-17 ☀️ 
- [  ] 供货范围清单页面 validator

**Comment by itomg** [comment]
#### 2016-08-18 ☀️ 
- [ ] igbug-29

**Comment by itomg** [comment]
#### 2016-08-19 ☀️ 
- [ ] igbug-32 select tree

**Comment by itomg** [comment]
#### 2016-08-22 ☀️ 
- [ ] backend project list pagination problem
- [ ] backend my project pages

**Comment by itomg** [comment]
#### 2016-08-23 ⛅ 
-  [ ] igbugs

**Comment by itomg** [comment]
#### 2016-08-24 ⛅ 
- [ ] igbugs

**Comment by itomg** [comment]
#### 2016-08-25 ⛅ 
- [ ] igbug-27

**Comment by itomg** [comment]
#### 2016-08-26 ☁️

**Comment by itomg** [comment]
#### 2016-08-29 ☁️ 
- [ ] igbugs

**Comment by itomg** [comment]
#### 2016-03-30 :umbrella:

**Comment by itomg** [comment]
#### 2016-08-31 ☔ 
```txt
现测试这边比较忙。对于后台项目管理，前面我只是大概过一遍，下面还得详细测试。

你们一是可以自己测测；另外还有“我的项目”没弄，目前只是模板，可以考虑弄下，看看有啥问题；三是前台页面初稿已经有了，我稍后传上去，可以考虑弄下。

很多方面后面肯定得优化，你们也可从用户或设计角度，多提建议，这是大家共同的作品。需求和表现，并非事先固定，还得咱们共同发掘。

“我的项目”根据不同角色，显示内容稍有不同，可以考虑先做客户（买家）角度的，内容基本是“项目管理”中的页面，暂时不考虑交互，只是显示已生成的设计、订单等信息。
```
