### ISSUE TITLE
Daily TODO list 2016 Sep

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#6]
💭 
#### prev #5

``` txt
现测试这边比较忙。对于后台项目管理，前面我只是大概过一遍，下面还得详细测试。

你们一是可以自己测测；另外还有“我的项目”没弄，目前只是模板，可以考虑弄下，看看有啥问题；三是前台页面初稿已经有了，我稍后传上去，可以考虑弄下。

很多方面后面肯定得优化，你们也可从用户或设计角度，多提建议，这是大家共同的作品。需求和表现，并非事先固定，还得咱们共同发掘。

“我的项目”根据不同角色，显示内容稍有不同，可以考虑先做客户（买家）角度的，内容基本是“项目管理”中的页面，暂时不考虑交互，只是显示已生成的设计、订单等信息。

你俩看看，分分工，前台优先，还有后台“我的项目”，尽快弄出来，这样才有一个原型，后面还有大量改进和优化
```

**Comment by itomg** [comment]
#### 2016-09-01 ☁️ 
- [ ] 前台页面分析

**Comment by itomg** [comment]
#### 2016-09-02 ✈️

**Comment by itomg** [comment]
#### 2016-09-05 ☁️ 
- [ ] backend myproject pages

**Comment by itomg** [comment]
#### 2016-09-06 ☁️ 
- [ ] backend myproject detail page
- [ ] backend myproject ? page

**Comment by itomg** [comment]
#### 2016-09-07 ☔ 
- [ ] backend myproject pages

**Comment by itomg** [comment]
#### 2016-09-08 ⛅ 
- [ ] backend myproject install pages

**Comment by itomg** [comment]
#### 2016-09-09 ☁️ 
- [ ]

**Comment by itomg** [comment]
#### 2016-09-12 ⛅ 
- [ ] frontend pages

**Comment by itomg** [comment]
#### 2016-09-13 ☁️ 
- [ ] image captcha
- [ ] mobile captcha

**Comment by itomg** [comment]
#### 2016-09-14 ☔ 
- [ ] Rewrite frontend supplier list page

**Comment by itomg** [comment]
#### 2016-09-18 ☁️ 
- [ ] igbug 51

**Comment by itomg** [comment]
#### 2016-09-19 ☀️ 
- [ ] igbug 54

**Comment by itomg** [comment]
#### 2016-09-20 ☀️ 
- [ ] igbug 54

**Comment by itomg** [comment]
#### 2016-09-21 ☀️ 
- [ ] igbug 54
  - [ ] captcha

**Comment by itomg** [comment]
#### 2016-09-22 ☀️ 
- [x] igbug 59

**Comment by itomg** [comment]
#### 2016-09-23 ☀️

**Comment by itomg** [comment]
#### 2016-09-26 ⛅ 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-09-28 ☁️ 
- [ ] igbug 58

**Comment by itomg** [comment]
#### 2016-09-29 ☔ 
- [ ] igbug 63

**Comment by itomg** [comment]
#### 2016-09-30 ☁️ 
- [ ] igbug 66
