### ISSUE TITLE
Daily TODO list 2016 Oct

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#7]
💭

**Comment by itomg** [comment]
#### 2016-10-08 ☔️ 
- [ ] igbug 70
- [ ] igbug 71
- [ ] igbug 72
- [ ] igbug 73

**Comment by itomg** [comment]
#### 2016-10-09 ☀️ 
- [ ] igbug 7*

**Comment by itomg** [comment]
#### 2016-10-10 ☀️ 
- [x] igbug 72

**Comment by itomg** [comment]
#### 2016-10-11 ☀️ 
- [ ] igbug 71 point 6

**Comment by itomg** [comment]
#### 2016-10-12 ☀️ 
- [ ] learning

**Comment by itomg** [comment]
#### 2016-10-13 ☀️ 
- [ ] learning

**Comment by itomg** [comment]
#### 2016-10-14 ☀️ 
- [ ] igbug 71

**Comment by itomg** [comment]
#### 2016-10-16 ☁️ 
- [ ] igbug

**Comment by itomg** [comment]
#### 2016-10-17 ☁️ 
- [ ] igbug 71 need rewrite
- [ ] igbug 84 need rewrite when fix igbug 71
- [ ] igbug 88 need rewrite
- [ ] igbug 87 fix when rewrite igbug 71

**Comment by itomg** [comment]
#### 2016-10-18 ☀️  
- [ ] igbug 71 need rewrite
  - 重构
    - [ ] backendProjectTransactionSupplier 供货商询价单列表页
- [ ] igbug 84 need rewrite when fix igbug 71
- [ ] igbug 88 need rewrite
- [ ] igbug 87 fix when rewrite igbug 71

**Comment by itomg** [comment]
#### 2016-10-19 ☁️ 
- [x] rewrite backend project transaction goods page
- [ ] rewrite backend project transaction order page

**Comment by itomg** [comment]
#### 2016-10-20 ☀️ 
- [ ] rewrite backend project transaction order page

**Comment by itomg** [comment]
#### 2016-10-21 ☀️ 
- [ ] igbug 94
- [ ] igbug 95
- [ ] rewrite backend project transaction supplier order page

**Comment by itomg** [comment]
#### 2016-10-24 ☀️ 
- [ ] task 4-5

**Comment by itomg** [comment]
#### 2016-10-25 ☁️ 
- [ ] task 4-5
  - [ ] product family pages
  - [ ] command & handler

**Comment by itomg** [comment]
#### 2016-10-25 ☁️ 
- [ ] task 4-5
  - [ ] product family add page show command error
  - [ ] product family edit page
  - [ ] product family list page
  - [ ] delete action & command & handler
  - [ ] fake id problem
  - [ ] too much th problem

**Comment by itomg** [comment]
#### 2016-10-25 ☀️ 
- [ ] task 4-7
- [ ] task 4-6

**Comment by itomg** [comment]
#### 2016-10-28 ☁️ 
- [ ] igbug 96
- [ ] task 4-6

**Comment by itomg** [comment]
#### 2016-10-31 ⛅️ 
- [ ] rewrite backend project transaction supplier order page
