### ISSUE TITLE
Daily TODO list 2016 Nov

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#8]
💭 
- [x] rewrite backend project transaction supplier order page
- [ ] rewrite backend project transaction supplier track page
- [ ] 已支付，才可以点击下一步
  - [ ] http://localhost:8000/backend/project/29/transaction/order
- [ ] phpstorm high cpu
- [ ] phpstorm database tool not work
- [ ] where to add business users
- [ ] return ArrayCollection in entities
- [x] add/edit product can't remove image

**Comment by itomg** [comment]
- [ ] igbug 100
- [ ] igbug 101
- [ ] igbug 102

**Comment by itomg** [comment]
#### 2016-11-02 ☀️ 
- [ ] igbug 103

**Comment by itomg** [comment]
#### 2016-11-03 ⛅️ 
- [ ] igbug 101

**Comment by itomg** [comment]
#### 2016-11-04 ☁️ 
- [ ] rewrite backend project transaction supplier order page

**Comment by itomg** [comment]
#### 2016-11-07 ❄️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-11-08 🌨 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-11-09 ☁️ 
- [ ] igbug 106
- [ ] igbug 107

**Comment by itomg** [comment]
#### 2016-11-10 ☁️ 
- [ ] igbug 108
- [ ] 在设计中，添加方案图片这里有问题，点了以后到其他的页面才弹出东西

**Comment by itomg** [comment]
#### 2016-11-11 🌨 
- [ ] igbug 112

**Comment by itomg** [comment]
#### 2016-11-14 ☁️ 
- [ ] 113
- [ ] 115
- [ ] 118

**Comment by itomg** [comment]
#### 2016-11-15 ☀️ 
- [ ] igbug 109

**Comment by itomg** [comment]
#### 2016-11-16 ☁️ 
- [ ] 前端的页面数据展示修复一下
  - [ ] 解决方案
  - [ ] 厂商

**Comment by itomg** [comment]
#### 2016-11-17 ☀️ 
- [ ] rewrite backend project transaction supplier track page
- [ ] 已支付，才可以点击下一步

**Comment by itomg** [comment]
#### 2016-11-18 ☁️ 
- [ ] new tables

**Comment by itomg** [comment]
#### 2016-11-21 ☔️ 
- [x] backend project category add design standard & typical supply
- [ ] frontend show project category design standard & typical supply

**Comment by itomg** [comment]
#### 2016-11-22 ☔️ 
- [ ] igbug 114
- [ ] igbug 119
- [ ] igbug 109

**Comment by itomg** [comment]
#### 2016-11-23 ☔️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-11-24 ⛅️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-11-25 ☁️ 
- [ ] ?

**Comment by itomg** [comment]
#### 2016-11-28
- [ ] ?

**Comment by itomg** [comment]
#### 2016-11-29 ☀️ 
- [ ] task 5-1

**Comment by itomg** [comment]
#### 2016-11-30 ☀️ 
- [ ] task 5-1
