### ISSUE TITLE
Daily TODO list 2016 Dec

### ISSUE THREAD

**Issue by itomg** [itomg/itomg.github.io#9]
💭 
- [ ] rewrite backend project transaction supplier track page
- [ ] 已支付，才可以点击下一步
  - [ ] http://localhost:8000/backend/project/29/transaction/order
- [ ] phpstorm high cpu
- [ ] phpstorm database tool not work
- [ ] where to add business users
- [ ] return ArrayCollection in entities

**Comment by itomg** [comment]
#### 2016-12-01 ☁️
- [ ] task 5-1
  - [ ] (5) new public product detail page
  - [ ] (4) new public supplier list page
  - [ ] (6) new public supplier detail page
  - [ ] (3) new public solution list page

**Comment by itomg** [comment]
#### 2016-12-02 ☀️ 
- [ ] igbug 120
- [ ] task 5-2

**Comment by itomg** [comment]
#### 2016-12-05 ☁️ 
- [ ] task 5-1 产品详情页，图片和产品描述，属性未显示单位
- [ ] task 5-2 登陆也未显示最新页面

**Comment by itomg** [comment]
#### 2016-12-06 ⛅️ 
- [x] task 5-3
  - [x] my business page
    - [ ] missing on/off icons
  - my personal page
    - [ ] 用户名，姓名，手机号 三个字段又出现歧义
    - [ ] 用户详情页出现允许编辑手机号的情况，出现 email 字段允许填写情况，注册时却没有
    - [ ] error or success messages no color style
    - [ ] missing + icon

**Comment by itomg** [comment]
#### 2016-12-07 ⛅️ 
- [ ] task 5-4
  - [ ] myproject
  - [ ] myproject/baseinfo

**Comment by itomg** [comment]
#### 2016-12-08 ☁️ 
- [ ] task 5-5
  - [ ] 项目设计：技术条件
  - [ ] 项目设计：项目文档
  - [ ] 项目设计：方案基本信息

**Comment by itomg** [comment]
#### 2016-12-09 🌨 
- [ ] task 5-6
  - [ ] 项目设计：供货范围清单
  - [ ] 项目设计：工程预算
  - [ ] 项目设计：方案文档

**Comment by itomg** [comment]
#### 2016-12-10 ⛅️ 
- [x] 5-7 前台注册逻辑的修改

**Comment by itomg** [comment]
#### 2016-12-11 ☁️ 
- [ ] 5-8 admin后台为项目添加负责人和日志记录
```
1. 数据表变动如下：

项目project表，添加字段admin_id （可为空，关联用户id），其含义是具有admin权限的所有用户

添加新表，project_log
id, project_id, admin_id（可为空）, note, created_at
其中project_id项目id, admin_id用户id, note为文本,created_at为日期时间(int)

2. admin后台页面变动如下：

所有项目>项目列表加一列“负责人”，显示admin_id对应的username，为空时不显示

所有项目>添加或修改项目基本信息的页面，相应添加负责人下拉列表，其中列出系统中所有权限是admin的username，可以选择其中一个作为负责人，当新指定或更改成某个下拉表中某admin_id时，还需要在project_log中记录一条：项目id,该admin_id,"Assigned by｛当前操作的用户username｝"

在项目的所有页面上，如技术条件、项目文档、供货范围清单。。。
(1)显示出该项目的负责人；
(2)增加一个div，按created_at时间排序(最新时间在上面)显示该项目的project_log表中记录，格式为：created_at admin_id对应的username: note<br/>，然后再加一个文本框textarea在最上面，供当前操作用户来录入日志，当录入日志非空时，提交后在project_log中新加一条记录：项目id, 操作用户id，录入的日志note，操作时间。
注: 该div可放到页面的顶部，可采用accordion样式
```

**Comment by itomg** [comment]
#### 2016-12-12 🌨 
- [ ] 5-9 前台首页左边和下面的咨询表单提交逻辑
```
前台左边"消音降噪免费咨询"和下面“免费咨询”，表单提交逻辑如下：

1.当用户未注册时，为该用户进行注册：
用户名设置为：“用户”＋用户id，
密码设置为：输入的电话号码后6位
其余同5-7前台注册逻辑

2.用户已注册，则为其创建一个项目：
项目类型为空
项目名称：未知项目＋项目id
项目来源：即该用户所属business_id
项目联系人：即该用户business_user_id
项目地点：即该用户在咨询中填写的地区
项目分类：为空（这个如果之前有非空要求，则需要改成可为空）

将该用户在咨询中填写的信息：称呼＋电话号码＋地区，作为日志note，在project_log表中添加一条记录：即项目id, admin_id为空，“称呼＋电话号码＋地区”，当前时间。


3 提交表单后的动作用command bus实现下面几个command
3.1 客户提交表单成功后，页面显示弹出框（内容稍后提供），显示project id
3.2 如果客户已经登录并且有email的话，发送邮件通知（内容未来提供），显示project id
3.3 向客户表单输入手机号码发送project id（具体内容未来提供）
3.4 如果客户已经登录并且绑定微信，则发送微信通知project id及内容（这个目前留个空的command就行）


注：前台表单称呼，省市，电话都为必填，如果有问题则像下图一样显示错误
```

**Comment by itomg** [comment]
#### 2016-12-13 ☁️ 
- [ ] 5-10 增加企业发票信息business_invoice
```
增加企业发票信息：

1.增加数据表business_invoice

id, 
business_id, 
title(发票抬头)，
mailing_address(邮寄地址)，
contact_name(联系人姓名)，
contact_phone(联系人电话)，
register_address(公司注册地址)，
tax_number(国税代码/纳税人识别号), 
bank(开户银行), 
account(银行账号), 
tax_phone（税务登记电话），
status,
created_at


2. 用户后台: 我的信息>发票信息

实现发票信息的显示和编辑功能
模板/template/ingreen/backend/myaccount/invoice
```

**Comment by itomg** [comment]
#### 2016-12-14 ⛅️ 
- [ ] task 5-10
- [ ] task 5-11

**Comment by itomg** [comment]
#### 2016-12-15 ☀️ 
- [ ] task 5-12
- [ ] task 5-13

**Comment by itomg** [comment]
#### 2016-12-16 ?
- [ ] task 5-13
- [ ] task 5-14
- [ ] 根据task 5-14中的说明来重新修复我的项目下能看到的项目列表

**Comment by itomg** [comment]
#### 2016-12-18 ☁️ 
- [ ] task 5-9

**Comment by itomg** [comment]
#### 2016-12-19 ☁️ 
- [ ] task 5-15
- [ ] task 5-16

**Comment by itomg** [comment]
#### 2016-12-20 ☁️ 
- [ ] task 5-15
  - [ ] my product add/edit doc
  - [ ] my product family quick form
- [ ] task 5-16

**Comment by itomg** [comment]
#### 2016-12-21 ☁️ 
- [ ] task 5-9

**Comment by itomg** [comment]
#### 2016-12-22 ☁️ 
- [ ] 修复 task 5-15 快速添加产品功能
- [ ] 用户注册用户名和密码登陆支持

**Comment by itomg** [comment]
#### 2016-12-23 ⛅️ 
- [ ] igbugs

**Comment by itomg** [comment]
#### 2016-12-24 ☀️ 
- [ ] igbug 126
- [ ] igbug 128
- [ ] igbug 129

**Comment by itomg** [comment]
#### 2016-12-26 ☁️ 
- [ ] igbug 129
- [ ] igbug 130
- [ ] igbug 131

**Comment by itomg** [comment]
#### 2016-12-27 ☀️ 
- [ ] 修改讨论时没有进入 bug 的部分

**Comment by itomg** [comment]
#### 2016-12-28 ⛅️ 
- [ ] igbug 132
- [ ] igbug 133

**Comment by itomg** [comment]
#### 2016-12-29 ☀️ 
- [x] fix project log admin id
- [ ] testing online

**Comment by itomg** [comment]
#### 2016-12-30 ☁️ 
- [ ] igbug 134

**Comment by itomg** [comment]
#### 2016-12-31 ☀️ 
- [ ] igbug 142 - 149

**Comment by itomg** [comment]
#### 2016-12-31 ☀️ 
- [ ] igbug 142 - 149
